### ISSUE TITLE
Add 'Privacy by design' competency

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#116]
Discussing with @sjwells (who in turn has been discussing with compliance and security people) - there is nothing in the competencies about understanding this principle.

I'm on the fence as to whether this should be a competency. Not to take away from its importance, I'm not convinced it is an easy one to provide evidence for. Also the competencies shouldn't become a dumping ground for whatever the business' current priorities are e.g. a year ago there might've been demand for a general 'Understands GDPR' competency

**Comment by sjwells** [comment]
I think considering privacy by design does fit into competencies - we should expect our principal engineers and seniors to be designing systems with privacy by design in mind.

Examples would be around making sure that :
- databases have encryption at rest
- sensitive data is masked or in restricted indexes in splunk
- data is retained only for as long as it is needed
- dummy/fictional data is used in staging environments and in tests
- suppliers don't get access to data unless they have gone through the PMA process

I think our guardrails should cover any other things we expect from people around data governance.
