### ISSUE TITLE
[M->S1 workshop feedback] There doesn't seem to be anything in the competencies about how systems fit together

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/engineering-progression#171]
This was raised my @pixelandpage in the mid level workshop. I'm transferring the issues from that workshop into GitHub for discussion but this is a more general point for someone to consider.

@pixelandpage I've tagged you in case when we come to address this we want to run stuff by you but there is no action required from you right now unless you'd like to make any suggestions/give further ideas.

**Comment by wheresrhys** [comment]
Thanks @pixelandpage - this does feel like an important omission. Here is a first draft of a competency to address this. Please can you let us know what you think. What would you give as examples?
---
Combines independent technical parts into a bigger whole to accomplish more complex requirements
- Deploys a data pipeline of sources, streams and consumers in AWS
- Writes a new origami component that uses other components
- Designs and implements a build pipeline using CI
- Implements a CDN / gateway that routes to a suite of underlying microservices

**Comment by pixelandpage** [comment]
Thanks @wheresrhys and @alicebartlett , this is great!

I was thinking about being able to reason about and work with the upstream/downstream context in system rather than the isolated parts so these are great examples.

For the sake of brainstorming, I might have come up with examples like:

 - Implementing a feature which relies on multiple data sources
 - Optimising part of an existing pipeline to the improve overall performance or reduce bottlenecks
 - Creates a diagram to document how the different parts of a complex system interact

**Comment by wheresrhys** [comment]
Yes I think yours are better @pixelandpage 	Some of mine are I think more S2 level. I will create a PR with the best of both

**Comment by wheresrhys** [comment]
addressed in #192
