### ISSUE TITLE
Need a 'staging environment'

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#253]
At wednesday's workshop it was frustrating that the website contained copies of the competencies that didn't reflect some of our significant recent updates. The yaml files on master are too dense a format to allow easy discovery.

Can we have an alternate publish destination for the master branch so it's easier to share the latest thinking prior to a tagged release

**Comment by rowanmanning** [comment]
I'm just releasing `v1.0.0-beta.2`. A staging environment might be useful, but because this is GitHub Pages and the way the spreadsheet script works I think it'd be a fair amount of effort to create it. 

Possibly we should just be a bit more vigilant with releasing and not leave `master` far ahead of the current tagged release?

**Comment by rowanmanning** [comment]
Moving to post-launch for now as I don't think it needs to be a focus immediately. @quarterto and I think that maybe we can find a different solution, e.g. only build the competency pages on a release rather than push to `master`
