### ISSUE TITLE
Is line management a non-promotable skill?

### ISSUE THREAD

**Issue by magsallen** [Financial-Times/engineering-progression#363]
Raising this as a potential issue in the S2 competencies.

It doesn't look like there is anywhere in the S2 competencies to include successes with regards to people management.

I know that line management is explicitly not a requirement for moving to either an S1 or an S2 level, and I absolutely agree with that, but it is a skill that most of our senior engineers are developing. Often S1s are line managing for the first time and having to learn new skills quickly so it feels like there should be a place to capture development in this area as part of tracking a person's readiness for promotion.

The closest competency that I can see is: [Identifies knowledge gaps within the team and gives training to address gaps](https://github.com/Financial-Times/engineering-progression/blob/main/data/competencies.yml#L1141) which doesn't quite seem to match what I'm thinking. It gives the impression that the skills I've been developing as a new line manager aren't going to help me move to the next level. 

At the S1 level, there is a Leadership competency for [Contributes to the personal development of more junior people](https://github.com/Financial-Times/engineering-progression/blob/main/data/competencies.yml#L943) which makes sense and which would be a good place to capture line management as well as other forms of people development.

It feels like there is a gap here. Or maybe a misalignment? Mentoring or helping other engineers to meet their career goals feels like a an engineering competency I would expect of all Seniors and one which can be done by peers without any formal people management roles being involved. I've had lots support from non-managers which has helped me become a better engineer.

If line management is not recognised in our engineering matrix then it could been seen as a non-promotable skill and I don't think that benefits us.

**Comment by AniaMakes** [comment]
This is an excellent point to raise. On one side we don't want people to think they MUST line manage to be promoted to S2, but also if they line manage, this should somehow count towards their promotion. 

We could change the competencies as follows:
- For S1's `Contributes to the personal development of more junior people` REMOVE the "is a line manager". I'm not really sure this is actually a reasonable example because when I expressed interest in line management it was made clear to me that as a Mid I couldn't line manage another Mid. So unless a Mid can line manage an Apprentice, this is moot point. And even then we get Apprentices relatively rarely. 
- For S2 add `Contributes to the personal development of more junior people` competency, with "is a line manager" as an example. We should figure out if some of the S1 examples for that competency could be shifted to sit here, so that it's clear that there are other ways to fulfil that point at S2 level.

**Comment by rowanmanning** [comment]
Thanks Maggie 🙂 and thanks Ania for a quick response. I'm gonna start with the fact that I agree we should add a new Senior 2 competency but wanted to point out a couple of things which will impact how we approach it.

  1. To progress towards S2, [you still need to be meeting competencies from earlier levels](https://engineering-progression.ft.com/docs/faq/#do-i-need-to-meet-competencies-from-earlier-levels). So the `Contributes to the personal development of more junior people` competency still applies, you don't get to progress to S1 and forget about developing other people around you

  2. Because of point 1, we don't duplicate exact competency summaries between levels. We only do so when the level above _expands_ on the competency, e.g.

      ```
      Mid: Regularly and independently debugs and fixes bugs in their own code
      ```

      ```
      S1: Regularly and independently debugs and fixes bugs regardless of origin
      ```

      So if we add a competency at S2 for this, the summary needs to indicate that there's a progression beyond the S1 competency. Up for suggestions on how you'd do that

  3. I wouldn't want to remove the `is a line manager` example from the S1 competency. It is a good example of contributing to someone's personal development, and removing it might give the impression that it's a non-promotable skill between mid and S1 and may discourage people from line managing if the opportunity is there. [Remember examples are just illustrative, you don't _need_ to do them](https://engineering-progression.ft.com/docs/faq/#do-i-need-to-provide-evidence-for-all-of-the-examples-in-a-competency).

**Comment by magsallen** [comment]
Perhaps we could build on the exiting competency but try to make it more active:
```S1: Contributes to the personal development of more junior people```
```S2: Encourages and shapes the personal development of more junior people```

**Comment by rowanmanning** [comment]
I like this suggestion, it illustrates a clear progression between the two levels 👍 I wonder whether we go with something more concrete as well to indicate that this is an active step an S2 should be taking?

```diff
- S2: Encourages and shapes the personal development of more junior people
+ S2: Actively encourages and shapes the personal development of more junior people
```

We'd need some examples of how this competency can be met. These are the ones from the S1 competency:

  - Is a line manager or mentor
  - Is a designated buddy to a new starter
  - Regularly meets up with more junior peers to provide guidance
  - Pairs with more junior team members
  - Writes blog posts to share knowledge
  - Gives talks at meet-ups or conferences to share knowledge

Let's think about whether any of these should move, or whether there are ways we can expand on these.

**Comment by magsallen** [comment]
I've had a think about this. I think the [S1 competencies](https://github.com/Financial-Times/engineering-progression/blob/main/data/competencies.yml#L943-L950) around developing more junior people should stay as they are. These have been agreed by the working group and they seem to be working for folks seeking promotion at this level. 

I'm proposing this as a new competency at S2 which builds on the examples in the S1 competency. Something like:

```
  summary: Actively encourages and shapes the personal development of more junior people
  examples:
    - Helps other engineers to meet specific career goals
    - Gives actionable feedback with examples of a behaviour and its impact
    - Organises conference attendance for a group of engineers
 ```
 
 Feedback needed! Especially if you disagree with the premise or the examples I've included

**Comment by AniaMakes** [comment]
I _think_ we would be better off using "proactively" rather than "actively"

> The dictionary says 'proactively' means to 'taking actions to control a situation rather than responding to it', and 'actively' means to do something in a passionate and vigorous way. 
> https://forum.wordreference.com/threads/actively-proactively-whats-the-difference.3651143

We want people to be doing this on their own initiative, rather than on somebody else's. It would go alongside an existing S2 competency `Identifies knowledge gaps within the team and gives training to address gaps`. 

> Helps other engineers to meet specific career goals
I would change this to "engages with other engineers to help them form career goals, and helps them to achieve those goal"

> Gives actionable feedback with examples of a behaviour and its impact
This should be S1 because the amount of non-actionable / personal opinion feedback I receive is 🙄 

> Organises conference attendance for a group of engineers
I'm not entirely sure how I fee about this point - I'm sorry, but I can't put my finger on it. It feels like this should be "I chat with Ashley and they tell me they are interested in X. Charlie - my acquaintance - is setting up a meetup in X. I tell Ashley this is the case and offer to make introductions".

**Comment by rowanmanning** [comment]
I like where this is going, I have a few small wording tweaks but wonder if it'd be better to move this to a pull request so that it's easier to raise thread discussions on specific examples? It might be easier to get a broad range of opinions once it looks like something concrete that could get merged too.

On the wording so far:

> Helps other engineers to meet specific career goals

I like this one and think we can encompass Ania's suggestion more simply:

```diff
-  - Helps other engineers to meet specific career goals
+  - Helps other engineers to form and meet specific career goals
```

> Gives actionable feedback with examples of a behaviour and its impact.

My only slight issue with this one is that we have competencies very similar to this already at the Engineer level, e.g. "Regularly gives timely actionable feedback to colleagues".

> Organises conference attendance for a group of engineers

I like this one, I think some more examples along these lines would be good, I'll have a think.

> **Ania:** It feels like this should be "I chat with Ashley and they tell me they are interested in X. Charlie - my acquaintance - is setting up a meetup in X. I tell Ashley this is the case and offer to make introductions".

If you can distill this down to a snappy sentence which outlines the behaviour we're after then that'd be great. It sounds a little like sponsorship, in this example what is the relationship between you and Ashley – is it line management? Peers?

**Comment by magsallen** [comment]
Thanks @AniaMakes and @rowanmanning for engaging with this  🙌 

It sounds like the 'feedback' example isn't quite working. I'll remove this if I can't think of a way to rephrase it.

On the 'Organises conference attendance' example, I was thinking of the work some engineers do in managing a list of people who are interested in attending a specific conference and getting sign off to ensure that tickets are approved and purchased on time. Is there a better way of phrasing this? If the meaning isn't coming across then I can rewrite or remove this one too.

I'm planning to move this to a PR soon so we might be able to generate more discussion there

**Comment by magsallen** [comment]
I've opened https://github.com/Financial-Times/engineering-progression/pull/365
