### ISSUE TITLE
Clarify "CTO organisation"

### ISSUE THREAD

**Issue by rowanbeentje** [Financial-Times/engineering-progression#78]
In the project description and documentation there's a few mentions that the scope of this progression project is the "CTO organisation". This feels like it means "anyone who ultimately reports to the FT Chief Technology Officer", but could that be explained more clearly, or explained via a Workday/other link?

**Comment by rowanmanning** [comment]
There's a PR open now #79, which was the result of a Slack conversation. Posting a transcript here as the discussion may be useful for someone searching the repo later:

**Adam Braimbridge:**

> What does CTO stand for?
> ![Screen-capture of the engineering progression website, contains the text: Engineering Progression, careers and progression for engineers in the CTO organisation at the FT](https://user-images.githubusercontent.com/138944/54612284-90e0c700-4a50-11e9-955f-bf0fb1de6c7c.png)


**Jake Champion:**

> I think it is The Tech part of Product & Tech

**Alice Bartlett**

> It is a good question Adam - basically, there are some engineers in the FT that do not ultimately report into John Kundert

> an easy example is FTLabs, who report into the Chief Product Officer

> a more complicated one is did you know there are some people that write front end code that work in the comms team?

> So - we can't say "all engineers at the FT" because that's not what we mean. If you have any suggestions for a better name I'd like that. You're not the first person to raise this.

> Until recently, Origami didn't report into JK either

**Comment by adambraimbridge** [comment]
Just thinking out loud: Could it be abstracted to a proposal or a standard, like [W3 standards](https://www.w3.org/standards/)? 

Not as formal of course, but in the same spirit ..? So in the documentation it could be something like this:

## FT Engineering Progression Standard
### Proposed career path and competencies for engineers

This might make it more useful to a public audience (and give FT more credibility?) because everyone (including us) can say, "we subscribe to version [n] of the FT Engineering Progression Standard"

**Comment by rowanmanning** [comment]
We're thinking we'll leave this as "CTO Organisation" but link somewhere (TBC) to explain what this means. We'd also like to clarify that engineers _outside_ of the CTO org, e.g. Labs, _can_ subscribe to this.

**Comment by alicebartlett** [comment]
@adambraimbridge that's an interesting suggestion but I don't think we should do that because
1. I don't want this to be a "standard" for which people are either "compliant" or "not complaint". People are not systems so I don't want to try to apply technical approaches to them.
2. I don't think people outside of the FT will want to use this work in that way. What we're already seeing is people copying the work and then modifying it to fit their org - which I think is the right approach.

**Comment by adambraimbridge** [comment]
Thanks Rowan and Alice, I'm nodding in agreement. 👍

**Comment by rowanmanning** [comment]
We're going to add the explainer to the FAQ section at some point after #168 is merged. Moving out of the Beta milestone for now.

**Comment by rowanmanning** [comment]
We now have [an FAQ](https://engineering-progression.ft.com/docs/faq/), so now if someone wants to add a "who does this apply to?" section then please feel free.
