### ISSUE TITLE
J->M feedback on certification/training

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/engineering-progression#82]
(breaking #80 into four separate issues for individual discussion)
2.  Nothing covers any certification, training or conference contributions; perhaps this is covered by `Takes ownership of personal development`?

**Comment by j-mes** [comment]
From #80 

This part is quite vague to me. The wording for the conference contributions: What does this mean? 
* Attending, volunteering or speaking?
* What counts and what does not count?

**Comment by wheresrhys** [comment]
I take it you're thinking of AWS associate in particular, which in Cloud Enablement is a prerequisite to becoming mid level?

This suggests 2 approaches to me
- some very specific competencies, so we'd have a `Attains AWS Associate certification` competency, which is only required for certain roles within engineering
- a generic `Attains required certification for their domain`, with examples provided. For roles where there is no required accreditation, it's a free tick

Perhaps others could chip in with other examples of accreditation which currently affect promotion decisions. Maybe AWS associate is the only one?

**Comment by rowanmanning** [comment]
This has been updated (#87), we now include some examples for the competency to illustrate what we're expecting:

> **Takes ownership of personal development**, e.g.
>  - Finds training course and takes it
>  - Studies for and attains a technical certification
>  - Proactively learns how to use a new tool/language feature

Thanks @jenniferemshepherd for raising and thanks @j-mes for contributing. I'm gonna close this issue, but if this is still not clear enough then we can reopen.

**Comment by sbinlondon** [comment]
Just to clarify - does this mean that things like speaking at conferences/meetups are _not_ considered for this, since it isn't listed as an example? @j-mes brought it up specifically but then it wasn't included so it makes me think it isn't counted.

**Comment by alicebartlett** [comment]
OK so- let's break down Jen's question.

```
2. Nothing covers any certification, training or conference contributions; perhaps this is covered by Takes ownership of personal development?
```

1. Certification and training are covered by the points already made here.
2. "Conference contributions" are a different thing and would be covered by a different competency.

There are a couple of other competencies that could be covered by speaking at conferences:
(J->M leadership) `Shares knowledge with peers informally` - this could have an example of speaking at a conf or a meet-up

**Comment by alicebartlett** [comment]
There are also some later competencies that could have an example:

`Contributes to hiring process` - Conferences are recruitment opportunities
`Influences a community of practice` - Although all the examples for this so far are internal. Perhaps that is the intention, I don't recall

**Comment by rowanmanning** [comment]
> does this mean that things like speaking at conferences/meetups are not considered for this, since it isn't listed as an example?

It's important to note that the examples are illustrations of things that _could_ meet the competency, and aren't an exhaustive list. This is now included in the [how to use the competencies](https://engineering-progression.ft.com/competencies/how-to-use/#examples) guide.

It was intentional that we didn't include a "shares knowledge outside of the FT" competency at the Junior to Mid level, as it's not something we expect of mid-level engineers. The competency that Alice mentions ("Shares knowledge with peers informally") _could_ be used as a proxy for this but this competency was more intended to encourage direct one-to-one or one-to-team knowledge share rather than broadcast communication.

I think `(M->S1) Influences a community of practice` should include examples of speaking at conferences and writing public blog posts, I've opened an issue here: #109.

**Comment by rowanmanning** [comment]
I'm going to close this again in favour of discussing in the new issue above.
