### ISSUE TITLE
Wording of "pragmatic decisions" competencies

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/engineering-progression#93]
_Opened on behalf of @JakeChampion after we ran through the competencies._

---

**Competency:** `97ac147f-1b61-43c4-b677-dbb837ba092b` (S1→S2, Technical)
> Makes pragmatic decisions about technical trade-offs…

It's possibly going to be difficult to provide evidence for something that an engineer chose _not_ to refactor or change. You'd need to provide evidence that you didn't do something.

Is there a way we can reword this or offer some additional examples?

**Comment by wheresrhys** [comment]
If it's a trade-off, won't the evidence be the thing they did instead of the thing they decided not to do? "Jake delivered x on time, partly because they made a conscious decision not to do y"?

At S1 -> S2 are we thinking that the trade-offs will be of sufficient scale to - in many cases - involve wider discussion with stakeholders, in which case these conversations could be referenced?

**Comment by alicebartlett** [comment]
[24/04/19]
We decided we need to take a look at the "technical tradeoffs" thread running from J->S2 and make sure they reflect the right changes across seniority.

**Comment by rowanmanning** [comment]
Moving to the Beta milestone, as this wasn't completed before the workshops.

**Comment by lc512k** [comment]
Resolved in https://github.com/Financial-Times/engineering-progression/pull/202
